version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Download HyperExecute CLI
      - run:
          name: Download HyperExecute CLI
          command: |
            curl -o hyperexecute https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
            chmod +x hyperexecute.exe
            ./hyperexecute.exe --user shubhamr --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh --config yaml/win/behave_hyperexecute_autosplit_sample.yaml --download-artifacts --download-report

